### ISSUE TITLE
Having issues when using the SaaSProductEntityDetail

### ISSUE THREAD

**Issue by jajreidy** [awslabs/aws-marketplace-catalog-api-shapes-for-python#3]
Seems at least in the product I'm using it has an extra field. I've checked to make sure the EntityType is SaaSProduct and the error I'm seeing is:

AttributeError: 'SaaSProductEntityDetail' object has no attribute 'region_availability'

**Comment by libohaAMZN** [comment]
Hello,

SaaSProductEntityDetail is intended to be used to deserialize the SaaSProduct JSON from a DescribeEntity call. Are you seeing this error when you are deserializing a JSON? Or are you trying to construct a SaaSProductEntityDetail object?

**Comment by jajreidy** [comment]
I'm seeing this error when trying to deserialize a JSON using DescribeEntity.

**Comment by libohaAMZN** [comment]
I assume you meant that you saw this error when you try to deserialize the JSON that was returned when you call Catalog API's DescribeEntity API.
We've confirmed via our unit tests that using the `.from_json` method that it should ignore unknown fields, including `region_availability`. We also were able to reproduce the error only if we try to access the field directly (e.g. `detail.region_availability`). Was this what you were trying to do?

**Comment by jajreidy** [comment]
I get the error when running .from_dict on DetailsDocument section of the return from describe_entity. I can try using from_json instead though.

**Comment by libohaAMZN** [comment]
Are you unblocked from the issue?

**Comment by jajreidy** [comment]
Yeah, this appears to be fixed. Thanks :)

**Comment by jajreidy** [comment]
Yeah, thanks this appears to be fixed. :)
